#!/bin/bash

#/
#--------------------------------------------------------------------------
# vpslara Mysql Password
#--------------------------------------------------------------------------
#
# This file will display the MySQL password
#
#/

. /etc/.vpslara/includes/colors
. /etc/.vpslara/includes/format

vpslara

MYSQLPASS=$(cat /etc/.vpslara/tmp/mysqlpass)

bar
cyan "| MySQL Password:"
cyan "| $MYSQLPASS"
bar